services:
  eva-backend-dev:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
      - ./Pages:/app/Pages
    environment:
      - NODE_ENV=development
    command: ["nodemon", "server.js"]

  eva-backend-prod:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile.prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    command: ["node", "server.js"]
