# Backend/Dockerfile.prod
FROM node:20-alpine
WORKDIR /app

COPY Backend/package*.json ./
RUN npm ci --only=production

COPY Backend/ /app/

# copys pages, use frontend in the future
COPY Pages/ /app/Pages/

EXPOSE 3000
CMD ["node", "server.js"]
