FROM node:20-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install
RUN npm install -g nodemon

COPY . .

ENV NODE_ENV=development

EXPOSE 3000
CMD ["nodemon", "server.js"]
